FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Entry point is defined in docker-compose.yml to allow waiting for the database
CMD ["python", "src/api.py"]
