FROM node:14-alpine

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

# Build the React app for production
RUN npm run build

# Install serve to run the application
RUN npm install -g serve

EXPOSE 3000

# Using serve to serve the built React app
CMD ["serve", "-s", "build", "-l", "3000"]